version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  vscode:
    image: codercom/code-server:latest
    container_name: vscode
    ports:
      - '8080:8080'
    volumes:
      - .:/home/coder/project
    environment:
      PASSWORD: 'yourpassword'

